name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/
    - name: Lint JavaScript source with standard.js
      run: |
        if [ ! -z "$NPM_PROXY" ]; then
          npm --registry=$NPM_PROXY install standard -g
        else
          npm install standard -g
        fi        
        standard   
    - name: Publish to NPM    
      run: |
        git config --global user.email "87917386+randomdev1234@users.noreply.github.com"
        git config --global user.name "Github Actions"
        npm version patch
        npm publish --access=public
        git add .
        git commit -m "Automated version increase"
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}
    - name: Push changes to Github
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automated version increase
        branch: ${{ github.head_ref }}
        commit_options: "--no-verify --signoff"
        repository: .
